language: generic
env:
  global:
    - CLI_VERSION=latest
before_install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - mv arduino-cli $HOME/bin/arduino-cli
  - mkdir -p $HOME/bin
  - arduino-cli config init
  - mv $PWD/travis/.cli-config.yml $HOME/.arduino15/arduino-cli.yaml
  - arduino-cli config dump
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index
  - arduino-cli core install arduino:avr
  - arduino-cli core install esp8266:esp8266
  - arduino-cli lib install "ShiftDisplay2"
  - arduino-cli lib install "RTClib"
  - touch Secrets.h
script:
  - arduino-cli compile --fqbn esp8266:esp8266:d1_mini $PWD/ArduinoClock.ino
